CREATE TABLE pagina_contacto (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hero_titulo VARCHAR(200) NOT NULL,
    hero_subtitulo TEXT,
    hero_imagen_url VARCHAR(255),
    info_titulo VARCHAR(100),
    info_descripcion TEXT,
    ubicacion_texto VARCHAR(200),
    mapa_url TEXT,
    cta_titulo VARCHAR(200),
    cta_descripcion TEXT,
    facebook_url VARCHAR(255),
    instagram_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    whatsapp_url VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO pagina_contacto (
    hero_titulo,
    hero_subtitulo,
    hero_imagen_url,
    info_titulo,
    info_descripcion,
    ubicacion_texto,
    mapa_url,
    cta_titulo,
    cta_descripcion
) VALUES (
    'Contáctanos',
    'Estamos aquí para ayudarte con tus proyectos. Escríbenos y te responderemos a la brevedad',
    '/contacto-hero.jpg',
    'Hablemos',
    'Nuestro equipo está disponible para atender tus consultas y brindarte la mejor solución para tus necesidades de equipos y servicios.',
    'Lima, Perú',
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62410.22785085749!2d-77.06418999999999!3d-12.046374!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c8b5e5b0c5e1%3A0x474f991d5d3f1b0a!2sLima%2C%20Per%C3%BA!5e0!3m2!1ses!2spe!4v1234567890',
    '¿Prefieres llamarnos directamente?',
    'Nuestro equipo está disponible de lunes a sábado para atender tus consultas'
);

ALTER TABLE pagina_contacto 
MODIFY COLUMN hero_titulo VARCHAR(200) NULL;


CREATE TABLE pagina_sobrenosotros (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hero_titulo VARCHAR(200) NULL,
    hero_subtitulo TEXT NULL,
    hero_imagen_url VARCHAR(255) NULL,
    intro_titulo VARCHAR(200) NULL,
    intro_descripcion TEXT NULL,
    intro_imagen_url VARCHAR(255) NULL,
    stat1_numero VARCHAR(50) NULL,
    stat1_label VARCHAR(100) NULL,
    stat2_numero VARCHAR(50) NULL,
    stat2_label VARCHAR(100) NULL,
    stat3_numero VARCHAR(50) NULL,
    stat3_label VARCHAR(100) NULL,
    historia_titulo VARCHAR(200) NULL,
    historia_descripcion TEXT NULL,
    timeline1_year VARCHAR(20) NULL,
    timeline1_desc VARCHAR(255) NULL,
    timeline2_year VARCHAR(20) NULL,
    timeline2_desc VARCHAR(255) NULL,
    timeline3_year VARCHAR(20) NULL,
    timeline3_desc VARCHAR(255) NULL,
    timeline4_year VARCHAR(20) NULL,
    timeline4_desc VARCHAR(255) NULL,
    mision_titulo VARCHAR(200) NULL,
    mision_texto TEXT NULL,
    vision_titulo VARCHAR(200) NULL,
    vision_texto TEXT NULL,
    dif1_titulo VARCHAR(200) NULL,
    dif1_descripcion TEXT NULL,
    dif2_titulo VARCHAR(200) NULL,
    dif2_descripcion TEXT NULL,
    dif3_titulo VARCHAR(200) NULL,
    dif3_descripcion TEXT NULL,
    dif4_titulo VARCHAR(200) NULL,
    dif4_descripcion TEXT NULL,
    cert_titulo VARCHAR(200) NULL,
    cert_descripcion TEXT NULL,
    cta_titulo VARCHAR(200) NULL,
    cta_descripcion TEXT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO pagina_sobrenosotros (
    hero_titulo,
    hero_subtitulo,
    intro_titulo,
    intro_descripcion,
    stat1_numero,
    stat1_label,
    stat2_numero,
    stat2_label,
    stat3_numero,
    stat3_label,
    historia_titulo,
    historia_descripcion,
    timeline1_year,
    timeline1_desc,
    timeline2_year,
    timeline2_desc,
    timeline3_year,
    timeline3_desc,
    timeline4_year,
    timeline4_desc,
    mision_titulo,
    mision_texto,
    vision_titulo,
    vision_texto,
    dif1_titulo,
    dif1_descripcion,
    dif2_titulo,
    dif2_descripcion,
    dif3_titulo,
    dif3_descripcion,
    dif4_titulo,
    dif4_descripcion,
    cert_titulo,
    cert_descripcion,
    cta_titulo,
    cta_descripcion
) VALUES (
    'Sobre Nosotros',
    'años de experiencia brindando soluciones integrales en arriendo de equipos',
    NULL,
    'En Ferreteria RyM, ofrecemos una amplia gama de equipos y herramientas en venta y arriendo',
    '24+',
    'Años de Experiencia',
    '100+',
    'Proyectos Completados',
    '50+',
    'Equipos Disponibles',
    'Historia',
    'Desde el año 2000, Ferreteria RyM ha sido un referente en Lima',
    NULL,
    'Fundacion de Ferreteria RyM',
    NULL,
    'Expansion de servicios y equipos especializados',
    NULL,
    'Reconocimiento como lideres en el sector',
    NULL,
    'Innovacion continua y tecnologia de vanguardia',
    'Mision',
    'Proveer soluciones integrales en arriendo de equipos',
    'Vision',
    'Ser la empresa lider en el arriendo de equipos',
    'Equipos Certificados',
    'Todos nuestros equipos cuentan con certificaciones vigentes',
    'Asesoria Especializada',
    'Contamos con un equipo tecnico altamente capacitado',
    'Respuesta Inmediata',
    'Disponibilidad inmediata de equipos',
    'Tecnologia de Vanguardia',
    'Renovacion constante de nuestra flota',
    'Certificaciones y Alianzas',
    'Mantenemos alianzas estrategicas con los principales fabricantes',
    'Listo para trabajar con nosotros?',
    'Contactanos hoy y descubre como podemos impulsar el exito de tu proximo proyecto'
);

CREATE TABLE pagina_certificaciones (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hero_titulo VARCHAR(200) NULL,
    hero_subtitulo TEXT NULL,
    hero_imagen_url VARCHAR(255) NULL,
    intro_titulo VARCHAR(200) NULL,
    intro_descripcion TEXT NULL,
    intro_imagen_url VARCHAR(255) NULL,
    beneficio1_icono VARCHAR(50) NULL,
    beneficio1_titulo VARCHAR(100) NULL,
    beneficio1_desc TEXT NULL,
    beneficio2_icono VARCHAR(50) NULL,
    beneficio2_titulo VARCHAR(100) NULL,
    beneficio2_desc TEXT NULL,
    beneficio3_icono VARCHAR(50) NULL,
    beneficio3_titulo VARCHAR(100) NULL,
    beneficio3_desc TEXT NULL,
    beneficio4_icono VARCHAR(50) NULL,
    beneficio4_titulo VARCHAR(100) NULL,
    beneficio4_desc TEXT NULL,
    proceso_titulo VARCHAR(200) NULL,
    paso1_numero VARCHAR(20) NULL,
    paso1_titulo VARCHAR(100) NULL,
    paso1_desc TEXT NULL,
    paso2_numero VARCHAR(20) NULL,
    paso2_titulo VARCHAR(100) NULL,
    paso2_desc TEXT NULL,
    paso3_numero VARCHAR(20) NULL,
    paso3_titulo VARCHAR(100) NULL,
    paso3_desc TEXT NULL,
    paso4_numero VARCHAR(20) NULL,
    paso4_titulo VARCHAR(100) NULL,
    paso4_desc TEXT NULL,
    requisitos_titulo VARCHAR(200) NULL,
    requisitos_descripcion TEXT NULL,
    req1_texto VARCHAR(255) NULL,
    req2_texto VARCHAR(255) NULL,
    req3_texto VARCHAR(255) NULL,
    req4_texto VARCHAR(255) NULL,
    req5_texto VARCHAR(255) NULL,
    req6_texto VARCHAR(255) NULL,
    testimonio1_nombre VARCHAR(100) NULL,
    testimonio1_cargo VARCHAR(100) NULL,
    testimonio1_empresa VARCHAR(100) NULL,
    testimonio1_texto TEXT NULL,
    testimonio1_imagen_url VARCHAR(255) NULL,
    testimonio2_nombre VARCHAR(100) NULL,
    testimonio2_cargo VARCHAR(100) NULL,
    testimonio2_empresa VARCHAR(100) NULL,
    testimonio2_texto TEXT NULL,
    testimonio2_imagen_url VARCHAR(255) NULL,
    testimonio3_nombre VARCHAR(100) NULL,
    testimonio3_cargo VARCHAR(100) NULL,
    testimonio3_empresa VARCHAR(100) NULL,
    testimonio3_texto TEXT NULL,
    testimonio3_imagen_url VARCHAR(255) NULL,
    certificadores_titulo VARCHAR(200) NULL,
    certificadores_descripcion TEXT NULL,
    cert_logo1_url VARCHAR(255) NULL,
    cert_logo2_url VARCHAR(255) NULL,
    cert_logo3_url VARCHAR(255) NULL,
    cert_logo4_url VARCHAR(255) NULL,
    cta_titulo VARCHAR(200) NULL,
    cta_descripcion TEXT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO pagina_certificaciones (
    hero_titulo,
    hero_subtitulo,
    intro_titulo,
    intro_descripcion,
    beneficio1_icono,
    beneficio1_titulo,
    beneficio1_desc,
    beneficio2_icono,
    beneficio2_titulo,
    beneficio2_desc,
    beneficio3_icono,
    beneficio3_titulo,
    beneficio3_desc,
    beneficio4_icono,
    beneficio4_titulo,
    beneficio4_desc,
    proceso_titulo,
    paso1_numero,
    paso1_titulo,
    paso1_desc,
    paso2_numero,
    paso2_titulo,
    paso2_desc,
    paso3_numero,
    paso3_titulo,
    paso3_desc,
    paso4_numero,
    paso4_titulo,
    paso4_desc,
    requisitos_titulo,
    requisitos_descripcion,
    req1_texto,
    req2_texto,
    req3_texto,
    req4_texto,
    req5_texto,
    req6_texto,
    testimonio1_nombre,
    testimonio1_cargo,
    testimonio1_empresa,
    testimonio1_texto,
    testimonio2_nombre,
    testimonio2_cargo,
    testimonio2_empresa,
    testimonio2_texto,
    testimonio3_nombre,
    testimonio3_cargo,
    testimonio3_empresa,
    testimonio3_texto,
    certificadores_titulo,
    certificadores_descripcion,
    cta_titulo,
    cta_descripcion
) VALUES (
    'Certificaciones Profesionales',
    'Programas de capacitación y certificación para operadores de equipos especializados',
    'Capacitación Certificada',
    'Ofrecemos programas de certificación reconocidos a nivel nacional para el manejo seguro y eficiente de equipos de construcción y tendido eléctrico',
    'school-outline',
    'Certificación Oficial',
    'Certificados avalados por entidades reguladoras',
    'people-outline',
    'Instructores Calificados',
    'Personal con amplia experiencia en el sector',
    'construct-outline',
    'Práctica Real',
    'Capacitación con equipos de última generación',
    'shield-checkmark-outline',
    'Seguridad Laboral',
    'Enfoque en normativas y protocolos de seguridad',
    'Proceso de Certificación',
    '01',
    'Inscripción',
    'Completa el formulario de inscripción y envía la documentación requerida',
    '02',
    'Capacitación',
    'Participa en las sesiones teóricas y prácticas programadas',
    '03',
    'Evaluación',
    'Aprueba las pruebas teóricas y prácticas de certificación',
    '04',
    'Certificación',
    'Recibe tu certificado oficial con validez nacional',
    'Requisitos',
    'Para inscribirte en nuestros programas de certificación debes cumplir con los siguientes requisitos',
    'Ser mayor de 18 años',
    'Documento de identidad vigente',
    'Certificado médico de aptitud',
    'Educación básica completa',
    'Experiencia previa (según programa)',
    'Fotografías tamaño carnet',
    'Carlos Mendoza',
    'Supervisor de Operaciones',
    'Constructora del Sur',
    'La certificación me permitió mejorar mis conocimientos y obtener mejores oportunidades laborales. El nivel de instrucción fue excelente',
    'María Torres',
    'Operadora de Grúas',
    'Proyectos Industriales SAC',
    'Un programa muy completo que combina teoría y práctica. Los instructores están muy bien preparados',
    'Roberto Silva',
    'Jefe de Mantenimiento',
    'Energía del Norte',
    'La capacitación superó mis expectativas. Ahora puedo operar los equipos con total seguridad y confianza',
    'Certificadores y Aliados',
    'Trabajamos con las principales entidades certificadoras del país para garantizar la validez de nuestros programas',
    '¿Listo para certificarte?',
    'Inscríbete en nuestros próximos programas de certificación y da el siguiente paso en tu carrera profesional'
);
CREATE TABLE pagina_arriendoequipos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hero_titulo VARCHAR(200) NULL,
    hero_subtitulo TEXT NULL,
    hero_imagen_url VARCHAR(255) NULL,
    tipo1_icono VARCHAR(50) NULL,
    tipo1_titulo VARCHAR(100) NULL,
    tipo1_desc TEXT NULL,
    tipo2_icono VARCHAR(50) NULL,
    tipo2_titulo VARCHAR(100) NULL,
    tipo2_desc TEXT NULL,
    catalogo_titulo VARCHAR(200) NULL,
    catalogo_descripcion TEXT NULL,
    video_url VARCHAR(255) NULL,
    video_poster_url VARCHAR(255) NULL,
    caracteristica1_titulo VARCHAR(100) NULL,
    caracteristica1_desc TEXT NULL,
    caracteristica2_titulo VARCHAR(100) NULL,
    caracteristica2_desc TEXT NULL,
    caracteristica3_titulo VARCHAR(100) NULL,
    caracteristica3_desc TEXT NULL,
    caracteristica4_titulo VARCHAR(100) NULL,
    caracteristica4_desc TEXT NULL,
    ventaja1_titulo VARCHAR(100) NULL,
    ventaja1_desc TEXT NULL,
    ventaja2_titulo VARCHAR(100) NULL,
    ventaja2_desc TEXT NULL,
    ventaja3_titulo VARCHAR(100) NULL,
    ventaja3_desc TEXT NULL,
    ventaja4_titulo VARCHAR(100) NULL,
    ventaja4_desc TEXT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO pagina_arriendoequipos (
    hero_titulo,
    hero_subtitulo,
    tipo1_icono,
    tipo1_titulo,
    tipo1_desc,
    tipo2_icono,
    tipo2_titulo,
    tipo2_desc,
    catalogo_titulo,
    catalogo_descripcion,
    caracteristica1_titulo,
    caracteristica1_desc,
    caracteristica2_titulo,
    caracteristica2_desc,
    caracteristica3_titulo,
    caracteristica3_desc,
    caracteristica4_titulo,
    caracteristica4_desc,
    ventaja1_titulo,
    ventaja1_desc,
    ventaja2_titulo,
    ventaja2_desc,
    ventaja3_titulo,
    ventaja3_desc,
    ventaja4_titulo,
    ventaja4_desc
) VALUES (
    'Arriendo de Equipos para Tendidos',
    'Soluciones especializadas para tendidos eléctricos aéreos y subterráneos',
    'flash-outline',
    'Tendido Aéreo',
    'Equipos especializados para la instalación y mantenimiento de líneas eléctricas aéreas. Maquinaria robusta y segura para trabajos en altura, garantizando eficiencia y protección en cada proyecto de electrificación.',
    'layers-outline',
    'Tendido Subterráneo',
    'Maquinaria especializada para la instalación de cables subterráneos. Equipos de precisión que facilitan el tendido de redes eléctricas bajo tierra, asegurando estabilidad y durabilidad en infraestructuras urbanas.',
    'Explora el Catálogo',
    'Explora nuestra amplia gama de equipos especializados para tendidos eléctricos aéreos y subterráneos. Descarga nuestro catálogo para conocer más sobre nuestras soluciones innovadoras, diseñadas para garantizar seguridad y eficiencia en tus proyectos.',
    'Calidad y Durabilidad',
    'Equipos robustos y de larga duración, ideales para entornos de trabajo exigentes.',
    'Tecnología Avanzada',
    'Equipos provistos de tecnología moderna que facilita un control preciso de la velocidad y tensión.',
    'Seguridad Garantizada',
    'Sistemas de seguridad integrados para proteger tanto a los operadores como a los equipos.',
    'Fácil Operación',
    'Diseño ergonómico que permite una operación sencilla y eficiente.',
    'Ahorro en Costos',
    'El arriendo de equipos reduce la inversión inicial y los costos de mantenimiento.',
    'Disponibilidad Inmediata',
    'Equipos listos para ser utilizados en cualquier momento.',
    'Asesoría Técnica',
    'Nuestro equipo de expertos está disponible para ofrecer soporte técnico durante todo el proceso.',
    'Flexibilidad',
    'Opciones de arriendo a corto y largo plazo para adaptarse a las necesidades de cada proyecto.'
);
