CREATE DATABASE IF NOT EXISTS ferreteria_rym
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ferreteria_rym;

CREATE TABLE empresa_info (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL DEFAULT 'Ferretería RyM',
    telefono VARCHAR(20) DEFAULT '+51 1 234 5678',
    email VARCHAR(100) DEFAULT 'contacto@ferreteriarym.pe',
    horario_lun_jue VARCHAR(50) DEFAULT '08:00 - 18:00',
    horario_vie VARCHAR(50) DEFAULT '08:00 - 18:00',
    horario_sab VARCHAR(50) DEFAULT '08:00 - 14:00',
    descripcion TEXT,
    historia TEXT,
    fecha_fundacion YEAR DEFAULT 2000,
    anios_experiencia INT DEFAULT 24,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE valores_empresa (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    orden INT DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE categorias_equipos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    tipo_tendido ENUM('aereo', 'subterraneo', 'ambos') DEFAULT 'ambos',
    imagen_url VARCHAR(255),
    orden INT DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE equipos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    categoria_id INT,
    codigo VARCHAR(50) UNIQUE NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    slug VARCHAR(150) UNIQUE NOT NULL,
    tipo VARCHAR(100),
    marca VARCHAR(100),
    modelo VARCHAR(100),
    capacidad VARCHAR(100),
    descripcion_corta VARCHAR(255),
    descripcion_completa TEXT,
    tecnologia TEXT,
    caracteristicas JSON,
    estado ENUM('disponible', 'arrendado', 'mantenimiento', 'reparacion', 'baja') DEFAULT 'disponible',
    stock INT DEFAULT 1,
    precio_dia DECIMAL(10,2),
    precio_semana DECIMAL(10,2),
    precio_mes DECIMAL(10,2),
    precio_compra DECIMAL(12,2),
    fecha_adquisicion DATE,
    garantia_meses INT,
    peso_kg DECIMAL(8,2),
    dimensiones VARCHAR(100),
    imagen_principal VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    destacado BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (categoria_id) REFERENCES categorias_equipos(id) ON DELETE SET NULL,
    INDEX idx_estado (estado),
    INDEX idx_activo (activo),
    INDEX idx_categoria (categoria_id)
);

CREATE TABLE imagenes_equipos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    equipo_id INT NOT NULL,
    url VARCHAR(255) NOT NULL,
    alt_text VARCHAR(255),
    orden INT DEFAULT 0,
    es_principal BOOLEAN DEFAULT FALSE,
    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (equipo_id) REFERENCES equipos(id) ON DELETE CASCADE,
    INDEX idx_equipo (equipo_id)
);

CREATE TABLE especificaciones_equipos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    equipo_id INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    valor VARCHAR(255) NOT NULL,
    unidad VARCHAR(50),
    orden INT DEFAULT 0,
    FOREIGN KEY (equipo_id) REFERENCES equipos(id) ON DELETE CASCADE,
    INDEX idx_equipo (equipo_id)
);

CREATE TABLE clientes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tipo_cliente ENUM('persona', 'empresa') NOT NULL,
    rut VARCHAR(20) UNIQUE NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    razon_social VARCHAR(200),
    giro VARCHAR(200),
    direccion VARCHAR(255),
    ciudad VARCHAR(100),
    region VARCHAR(100),
    pais VARCHAR(100) DEFAULT 'Perú',
    telefono VARCHAR(20),
    telefono_alternativo VARCHAR(20),
    email VARCHAR(100) NOT NULL,
    contacto_nombre VARCHAR(150),
    contacto_cargo VARCHAR(100),
    contacto_telefono VARCHAR(20),
    contacto_email VARCHAR(100),
    credito_aprobado BOOLEAN DEFAULT FALSE,
    limite_credito DECIMAL(12,2) DEFAULT 0,
    descuento_porcentaje DECIMAL(5,2) DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    notas TEXT,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rut (rut),
    INDEX idx_email (email),
    INDEX idx_activo (activo)
);

CREATE TABLE arriendos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    numero_contrato VARCHAR(50) UNIQUE NOT NULL,
    cliente_id INT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin_estimada DATE NOT NULL,
    fecha_fin_real DATE,
    dias_totales INT NOT NULL,
    tipo_arriendo ENUM('diario', 'semanal', 'mensual', 'personalizado') DEFAULT 'diario',
    modalidad ENUM('corto_plazo', 'largo_plazo') DEFAULT 'corto_plazo',
    estado ENUM('borrador', 'cotizacion', 'aprobado', 'activo', 'finalizado', 'cancelado') DEFAULT 'borrador',
    lugar_entrega VARCHAR(255),
    direccion_entrega VARCHAR(255),
    lugar_devolucion VARCHAR(255),
    requiere_transporte BOOLEAN DEFAULT FALSE,
    costo_transporte DECIMAL(10,2) DEFAULT 0,
    requiere_operador BOOLEAN DEFAULT FALSE,
    costo_operador DECIMAL(10,2) DEFAULT 0,
    garantia_deposito DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
    descuento_porcentaje DECIMAL(5,2) DEFAULT 0,
    descuento_monto DECIMAL(12,2) DEFAULT 0,
    iva DECIMAL(12,2) DEFAULT 0,
    total DECIMAL(12,2) NOT NULL DEFAULT 0,
    observaciones TEXT,
    condiciones_especiales TEXT,
    usuario_creacion VARCHAR(100),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    INDEX idx_cliente (cliente_id),
    INDEX idx_estado (estado),
    INDEX idx_fecha_inicio (fecha_inicio),
    INDEX idx_numero_contrato (numero_contrato)
);

CREATE TABLE detalle_arriendos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    arriendo_id INT NOT NULL,
    equipo_id INT NOT NULL,
    cantidad INT NOT NULL DEFAULT 1,
    precio_unitario DECIMAL(10,2) NOT NULL,
    unidad_tiempo ENUM('dia', 'semana', 'mes') NOT NULL,
    cantidad_tiempo INT NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    fecha_entrega_real DATETIME,
    fecha_devolucion_real DATETIME,
    estado_equipo_entrega TEXT,
    estado_equipo_devolucion TEXT,
    estado ENUM('pendiente', 'entregado', 'en_uso', 'devuelto', 'con_problemas') DEFAULT 'pendiente',
    dias_mora INT DEFAULT 0,
    cargo_mora DECIMAL(10,2) DEFAULT 0,
    observaciones TEXT,
    FOREIGN KEY (arriendo_id) REFERENCES arriendos(id) ON DELETE CASCADE,
    FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    INDEX idx_arriendo (arriendo_id),
    INDEX idx_equipo (equipo_id),
    INDEX idx_estado (estado)
);

CREATE TABLE pagos_arriendos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    arriendo_id INT NOT NULL,
    numero_pago VARCHAR(50) UNIQUE NOT NULL,
    tipo_pago ENUM('anticipo', 'parcial', 'total', 'garantia', 'mora', 'adicional') NOT NULL,
    monto DECIMAL(12,2) NOT NULL,
    metodo_pago ENUM('efectivo', 'transferencia', 'cheque', 'tarjeta_credito', 'tarjeta_debito') NOT NULL,
    estado ENUM('pendiente', 'recibido', 'confirmado', 'anulado') DEFAULT 'pendiente',
    fecha_programada DATE,
    fecha_pago DATETIME,
    numero_documento VARCHAR(100),
    banco VARCHAR(100),
    observaciones TEXT,
    usuario_registro VARCHAR(100),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (arriendo_id) REFERENCES arriendos(id) ON DELETE CASCADE,
    INDEX idx_arriendo (arriendo_id),
    INDEX idx_estado (estado)
);

CREATE TABLE tipos_servicio (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    descripcion_corta VARCHAR(255),
    icono VARCHAR(50),
    tiempo_estimado_horas INT,
    precio_base DECIMAL(10,2),
    activo BOOLEAN DEFAULT TRUE,
    orden INT DEFAULT 0,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ordenes_servicio (
    id INT PRIMARY KEY AUTO_INCREMENT,
    numero_orden VARCHAR(50) UNIQUE NOT NULL,
    cliente_id INT,
    equipo_id INT,
    tipo_servicio_id INT NOT NULL,
    fecha_solicitud DATETIME NOT NULL,
    fecha_programada DATETIME,
    fecha_inicio DATETIME,
    fecha_completada DATETIME,
    prioridad ENUM('baja', 'media', 'alta', 'urgente') DEFAULT 'media',
    estado ENUM('solicitado', 'aprobado', 'programado', 'en_proceso', 'pausado', 'completado', 'cancelado') DEFAULT 'solicitado',
    sintomas_reportados TEXT,
    diagnostico TEXT,
    trabajo_realizado TEXT,
    recomendaciones TEXT,
    costo_mano_obra DECIMAL(10,2) DEFAULT 0,
    costo_repuestos DECIMAL(10,2) DEFAULT 0,
    costo_adicionales DECIMAL(10,2) DEFAULT 0,
    costo_total DECIMAL(10,2) DEFAULT 0,
    horas_trabajadas DECIMAL(5,2),
    tecnico_asignado VARCHAR(100),
    tecnico_responsable VARCHAR(100),
    calificacion_cliente INT,
    comentario_cliente TEXT,
    observaciones TEXT,
    usuario_creacion VARCHAR(100),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    FOREIGN KEY (tipo_servicio_id) REFERENCES tipos_servicio(id),
    INDEX idx_cliente (cliente_id),
    INDEX idx_equipo (equipo_id),
    INDEX idx_estado (estado),
    INDEX idx_numero_orden (numero_orden)
);

CREATE TABLE repuestos_servicio (
    id INT PRIMARY KEY AUTO_INCREMENT,
    orden_servicio_id INT NOT NULL,
    codigo_repuesto VARCHAR(50),
    nombre_repuesto VARCHAR(150) NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    proveedor VARCHAR(150),
    FOREIGN KEY (orden_servicio_id) REFERENCES ordenes_servicio(id) ON DELETE CASCADE,
    INDEX idx_orden (orden_servicio_id)
);

CREATE TABLE mantenimiento_preventivo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    equipo_id INT NOT NULL,
    tipo_mantenimiento VARCHAR(100) NOT NULL,
    descripcion TEXT,
    frecuencia_dias INT NOT NULL,
    ultima_fecha DATE,
    proxima_fecha DATE NOT NULL,
    estado ENUM('programado', 'realizado', 'vencido', 'cancelado') DEFAULT 'programado',
    orden_servicio_id INT,
    notificacion_enviada BOOLEAN DEFAULT FALSE,
    observaciones TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (equipo_id) REFERENCES equipos(id) ON DELETE CASCADE,
    FOREIGN KEY (orden_servicio_id) REFERENCES ordenes_servicio(id) ON DELETE SET NULL,
    INDEX idx_equipo (equipo_id),
    INDEX idx_proxima_fecha (proxima_fecha),
    INDEX idx_estado (estado)
);

CREATE TABLE programas_certificacion (
    id INT PRIMARY KEY AUTO_INCREMENT,
    codigo VARCHAR(50) UNIQUE NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    slug VARCHAR(150) UNIQUE NOT NULL,
    descripcion TEXT,
    descripcion_corta VARCHAR(255),
    tipo ENUM('equipos', 'operadores', 'mixto') DEFAULT 'mixto',
    nivel ENUM('basico', 'intermedio', 'avanzado') DEFAULT 'basico',
    duracion_horas INT NOT NULL,
    duracion_dias INT,
    horas_teoricas INT,
    horas_practicas INT,
    costo DECIMAL(10,2) NOT NULL,
    cupos_minimo INT DEFAULT 1,
    cupos_maximo INT DEFAULT 20,
    contenido_teorico TEXT,
    contenido_practico TEXT,
    requisitos TEXT,
    beneficios TEXT,
    incluye TEXT,
    certificado_vigencia_meses INT,
    imagen_url VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    destacado BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_activo (activo),
    INDEX idx_tipo (tipo)
);

CREATE TABLE cursos_programados (
    id INT PRIMARY KEY AUTO_INCREMENT,
    programa_id INT NOT NULL,
    codigo_curso VARCHAR(50) UNIQUE NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    horario VARCHAR(100),
    lugar VARCHAR(255),
    direccion TEXT,
    instructor VARCHAR(150),
    cupos_disponibles INT NOT NULL,
    cupos_ocupados INT DEFAULT 0,
    estado ENUM('programado', 'confirmado', 'en_curso', 'completado', 'cancelado') DEFAULT 'programado',
    observaciones TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (programa_id) REFERENCES programas_certificacion(id),
    INDEX idx_programa (programa_id),
    INDEX idx_fecha_inicio (fecha_inicio),
    INDEX idx_estado (estado)
);

CREATE TABLE certificaciones (
    id INT PRIMARY KEY AUTO_INCREMENT,
    curso_id INT NOT NULL,
    numero_certificado VARCHAR(50) UNIQUE,
    participante_nombre VARCHAR(150) NOT NULL,
    participante_rut VARCHAR(20) NOT NULL,
    participante_email VARCHAR(100),
    participante_telefono VARCHAR(20),
    participante_empresa VARCHAR(150),
    participante_cargo VARCHAR(100),
    fecha_inscripcion DATE NOT NULL,
    estado_inscripcion ENUM('inscrito', 'confirmado', 'en_curso', 'aprobado', 'reprobado', 'retirado', 'cancelado') DEFAULT 'inscrito',
    asistencia_porcentaje DECIMAL(5,2),
    calificacion_teorica DECIMAL(5,2),
    calificacion_practica DECIMAL(5,2),
    calificacion_final DECIMAL(5,2),
    estado_aprobacion ENUM('pendiente', 'aprobado', 'reprobado') DEFAULT 'pendiente',
    fecha_emision_certificado DATE,
    fecha_vencimiento_certificado DATE,
    certificado_pdf_url VARCHAR(255),
    monto_pagado DECIMAL(10,2),
    estado_pago ENUM('pendiente', 'parcial', 'pagado') DEFAULT 'pendiente',
    observaciones TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (curso_id) REFERENCES cursos_programados(id),
    INDEX idx_curso (curso_id),
    INDEX idx_participante_rut (participante_rut),
    INDEX idx_estado (estado_inscripcion)
);

CREATE TABLE galeria (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(150),
    descripcion TEXT,
    categoria ENUM('equipos', 'proyectos', 'certificaciones', 'instalaciones', 'taller', 'eventos', 'otros') DEFAULT 'otros',
    tipo_contenido ENUM('imagen', 'video') DEFAULT 'imagen',
    url VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(255),
    alt_text VARCHAR(255),
    orden INT DEFAULT 0,
    destacado BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_categoria (categoria),
    INDEX idx_activo (activo)
);

CREATE TABLE catalogos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    categoria VARCHAR(100),
    archivo_url VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(50),
    tamano_kb INT,
    version VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE,
    destacado BOOLEAN DEFAULT FALSE,
    descargas INT DEFAULT 0,
    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_activo (activo)
);

CREATE TABLE formulario_contacto (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(150) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    empresa VARCHAR(150),
    asunto VARCHAR(200) NOT NULL,
    mensaje TEXT NOT NULL,
    tipo_consulta ENUM('arriendo', 'servicio_tecnico', 'certificacion', 'cotizacion', 'reclamo', 'general') DEFAULT 'general',
    origen ENUM('web', 'telefono', 'email', 'presencial', 'whatsapp') DEFAULT 'web',
    estado ENUM('nuevo', 'en_revision', 'contactado', 'respondido', 'cerrado', 'spam') DEFAULT 'nuevo',
    prioridad ENUM('baja', 'media', 'alta') DEFAULT 'media',
    ip_address VARCHAR(45),
    user_agent TEXT,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_primera_respuesta TIMESTAMP NULL,
    fecha_cierre TIMESTAMP NULL,
    asignado_a VARCHAR(100),
    respuesta TEXT,
    notas_internas TEXT,
    INDEX idx_estado (estado),
    INDEX idx_tipo_consulta (tipo_consulta),
    INDEX idx_fecha_envio (fecha_envio)
);

CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    rol ENUM('admin', 'cliente') NOT NULL DEFAULT 'cliente',
    cliente_id INT NULL,
    avatar_url VARCHAR(255),
    telefono VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE,
    email_verificado BOOLEAN DEFAULT FALSE,
    fecha_verificacion_email TIMESTAMP NULL,
    token_recuperacion VARCHAR(255),
    token_expiracion TIMESTAMP NULL,
    ultimo_acceso TIMESTAMP NULL,
    intentos_fallidos INT DEFAULT 0,
    bloqueado_hasta TIMESTAMP NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL,
    INDEX idx_username (username),
    INDEX idx_email (email),
    INDEX idx_rol (rol),
    INDEX idx_activo (activo)
);

CREATE TABLE permisos_admin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    usuario_id INT NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    puede_ver BOOLEAN DEFAULT TRUE,
    puede_crear BOOLEAN DEFAULT FALSE,
    puede_editar BOOLEAN DEFAULT FALSE,
    puede_eliminar BOOLEAN DEFAULT FALSE,
    puede_exportar BOOLEAN DEFAULT FALSE,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE KEY unique_usuario_modulo (usuario_id, modulo),
    INDEX idx_usuario (usuario_id),
    INDEX idx_modulo (modulo)
);

CREATE TABLE sesiones_usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    usuario_id INT NOT NULL,
    token VARCHAR(255) UNIQUE NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    fecha_inicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP NOT NULL,
    activa BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    INDEX idx_usuario (usuario_id),
    INDEX idx_token (token),
    INDEX idx_activa (activa)
);

CREATE TABLE configuracion_sistema (
    id INT PRIMARY KEY AUTO_INCREMENT,
    clave VARCHAR(100) UNIQUE NOT NULL,
    valor TEXT,
    tipo ENUM('texto', 'numero', 'boolean', 'json') DEFAULT 'texto',
    descripcion TEXT,
    grupo VARCHAR(50),
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE auditoria (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tabla VARCHAR(100) NOT NULL,
    registro_id INT NOT NULL,
    accion ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
    datos_anteriores JSON,
    datos_nuevos JSON,
    usuario_id INT,
    ip_address VARCHAR(45),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_tabla (tabla),
    INDEX idx_fecha (fecha),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

INSERT INTO empresa_info (nombre, telefono, email, descripcion, historia, fecha_fundacion, anios_experiencia)
VALUES (
    'Ferretería RyM',
    '+51 1 234 5678',
    'contacto@ferreteriarym.pe',
    'En Ferretería RyM, ofrecemos una amplia gama de equipos y herramientas en venta y arriendo, diseñados para satisfacer las necesidades de proyectos de construcción, mantenimiento y obras en general.',
    'Desde el año 2000, Ferretería RyM ha sido un referente en Lima, brindando soluciones integrales en herramientas, equipos y materiales de construcción.',
    2000,
    24
);

INSERT INTO valores_empresa (nombre, descripcion, orden) VALUES
('Calidad', 'Ofrecemos productos y servicios de la más alta calidad para nuestros clientes.', 1),
('Confianza', 'Construimos relaciones duraderas basadas en la confianza y transparencia.', 2),
('Servicio', 'Brindamos atención personalizada y asesoría especializada.', 3),
('Experiencia', 'Más de 20 años respaldando proyectos en Lima y todo el Perú.', 4),
('Innovación', 'Incorporamos constantemente nuevas tecnologías y equipos al mercado peruano.', 5),
('Compromiso', 'Comprometidos con el éxito de cada proyecto de nuestros clientes.', 6);

INSERT INTO categorias_equipos (nombre, slug, descripcion, tipo_tendido) VALUES
('Equipos de Construcción', 'equipos-construccion', 'Maquinaria pesada para construcción y obras civiles', 'ambos'),
('Herramientas Eléctricas', 'herramientas-electricas', 'Herramientas eléctricas profesionales', 'ambos'),
('Equipos de Altura', 'equipos-altura', 'Andamios, escaleras y plataformas', 'aereo'),
('Equipos de Excavación', 'equipos-excavacion', 'Equipos para movimiento de tierra', 'subterraneo');

INSERT INTO tipos_servicio (nombre, slug, descripcion, descripcion_corta) VALUES
('Mantenimiento de Equipos', 'mantenimiento-equipos', 'Servicio de mantenimiento preventivo y correctivo para equipos.', 'Mantenimiento especializado'),
('Reparación General', 'reparacion-general', 'Reparación de herramientas y equipos de construcción.', 'Reparación profesional'),
('Asesoría Técnica', 'asesoria-tecnica', 'Asesoría para selección y uso correcto de equipos.', 'Asesoría especializada'),
('Capacitación', 'capacitacion', 'Capacitación en uso seguro de equipos y herramientas.', 'Entrenamiento profesional'),
('Instalación de Equipos', 'instalacion-equipos', 'Servicio de instalación y puesta en marcha.', 'Instalación completa');

INSERT INTO configuracion_sistema (clave, valor, tipo, descripcion, grupo) VALUES
('igv_porcentaje', '18', 'numero', 'Porcentaje de IGV aplicable en Perú', 'facturacion'),
('mora_porcentaje_diario', '1', 'numero', 'Porcentaje de mora diaria', 'arriendos'),
('email_notificaciones', 'contacto@ferreteriarym.pe', 'texto', 'Email para notificaciones del sistema', 'general'),
('dias_anticipo_mantenimiento', '7', 'numero', 'Días de anticipación para avisos de mantenimiento', 'mantenimiento'),
('garantia_deposito_porcentaje', '30', 'numero', 'Porcentaje del total como depósito de garantía', 'arriendos'),
('moneda', 'PEN', 'texto', 'Moneda del sistema (Soles peruanos)', 'general'),
('zona_horaria', 'America/Lima', 'texto', 'Zona horaria del sistema', 'general');


ALTER TABLE empresa_info 
ADD COLUMN logo_url VARCHAR(255) NULL AFTER anios_experiencia;



CREATE TABLE pagina_serviciotecnico (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hero_titulo VARCHAR(200) NULL,
    hero_subtitulo TEXT NULL,
    hero_imagen_url VARCHAR(255) NULL,
    intro_titulo VARCHAR(200) NULL,
    intro_descripcion TEXT NULL,
    servicio1_icono VARCHAR(50) NULL,
    servicio1_titulo VARCHAR(100) NULL,
    servicio1_desc TEXT NULL,
    servicio2_icono VARCHAR(50) NULL,
    servicio2_titulo VARCHAR(100) NULL,
    servicio2_desc TEXT NULL,
    servicio3_icono VARCHAR(50) NULL,
    servicio3_titulo VARCHAR(100) NULL,
    servicio3_desc TEXT NULL,
    servicio4_icono VARCHAR(50) NULL,
    servicio4_titulo VARCHAR(100) NULL,
    servicio4_desc TEXT NULL,
    destacado1_icono VARCHAR(50) NULL,
    destacado1_titulo VARCHAR(100) NULL,
    destacado1_desc TEXT NULL,
    destacado1_feature1 VARCHAR(100) NULL,
    destacado1_feature2 VARCHAR(100) NULL,
    destacado1_feature3 VARCHAR(100) NULL,
    destacado1_feature4 VARCHAR(100) NULL,
    destacado2_icono VARCHAR(50) NULL,
    destacado2_titulo VARCHAR(100) NULL,
    destacado2_desc TEXT NULL,
    destacado2_feature1 VARCHAR(100) NULL,
    destacado2_feature2 VARCHAR(100) NULL,
    destacado2_feature3 VARCHAR(100) NULL,
    destacado2_feature4 VARCHAR(100) NULL,
    beneficio1_icono VARCHAR(50) NULL,
    beneficio1_titulo VARCHAR(100) NULL,
    beneficio1_desc TEXT NULL,
    beneficio2_icono VARCHAR(50) NULL,
    beneficio2_titulo VARCHAR(100) NULL,
    beneficio2_desc TEXT NULL,
    beneficio3_icono VARCHAR(50) NULL,
    beneficio3_titulo VARCHAR(100) NULL,
    beneficio3_desc TEXT NULL,
    beneficio4_icono VARCHAR(50) NULL,
    beneficio4_titulo VARCHAR(100) NULL,
    beneficio4_desc TEXT NULL,
    beneficio5_icono VARCHAR(50) NULL,
    beneficio5_titulo VARCHAR(100) NULL,
    beneficio5_desc TEXT NULL,
    beneficio6_icono VARCHAR(50) NULL,
    beneficio6_titulo VARCHAR(100) NULL,
    beneficio6_desc TEXT NULL,
    proceso_titulo VARCHAR(200) NULL,
    paso1_titulo VARCHAR(100) NULL,
    paso1_desc TEXT NULL,
    paso2_titulo VARCHAR(100) NULL,
    paso2_desc TEXT NULL,
    paso3_titulo VARCHAR(100) NULL,
    paso3_desc TEXT NULL,
    paso4_titulo VARCHAR(100) NULL,
    paso4_desc TEXT NULL,
    paso5_titulo VARCHAR(100) NULL,
    paso5_desc TEXT NULL,
    paso6_titulo VARCHAR(100) NULL,
    paso6_desc TEXT NULL,
    cta_titulo VARCHAR(200) NULL,
    cta_descripcion TEXT NULL,
    cta_nota VARCHAR(255) NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO pagina_serviciotecnico (
    hero_titulo,
    hero_subtitulo,
    intro_titulo,
    intro_descripcion,
    servicio1_icono,
    servicio1_titulo,
    servicio1_desc,
    servicio2_icono,
    servicio2_titulo,
    servicio2_desc,
    servicio3_icono,
    servicio3_titulo,
    servicio3_desc,
    servicio4_icono,
    servicio4_titulo,
    servicio4_desc,
    destacado1_icono,
    destacado1_titulo,
    destacado1_desc,
    destacado1_feature1,
    destacado1_feature2,
    destacado1_feature3,
    destacado1_feature4,
    destacado2_icono,
    destacado2_titulo,
    destacado2_desc,
    destacado2_feature1,
    destacado2_feature2,
    destacado2_feature3,
    destacado2_feature4,
    beneficio1_icono,
    beneficio1_titulo,
    beneficio1_desc,
    beneficio2_icono,
    beneficio2_titulo,
    beneficio2_desc,
    beneficio3_icono,
    beneficio3_titulo,
    beneficio3_desc,
    beneficio4_icono,
    beneficio4_titulo,
    beneficio4_desc,
    beneficio5_icono,
    beneficio5_titulo,
    beneficio5_desc,
    beneficio6_icono,
    beneficio6_titulo,
    beneficio6_desc,
    proceso_titulo,
    paso1_titulo,
    paso1_desc,
    paso2_titulo,
    paso2_desc,
    paso3_titulo,
    paso3_desc,
    paso4_titulo,
    paso4_desc,
    paso5_titulo,
    paso5_desc,
    paso6_titulo,
    paso6_desc,
    cta_titulo,
    cta_descripcion,
    cta_nota
) VALUES (
    'Servicio Técnico',
    'Mantenimiento y reparación de equipos de alta calidad',
    'Explora el Servicio Técnico de Ferretería RyM',
    'En Ferretería RyM contamos con un equipo técnico altamente calificado y experimentado en el mantenimiento, reparación y optimización de equipos para tendidos eléctricos. Nuestro compromiso es mantener sus equipos operando al máximo rendimiento, minimizando tiempos de inactividad y garantizando la seguridad de sus operaciones.',
    'search-outline',
    'Diagnóstico y Solución',
    'Identificación y resolución rápida de problemas en sus equipos con nuestros servicios de diagnóstico técnico. Mantenga sus operaciones sin interrupciones con análisis profundo y soluciones efectivas.',
    'construct-outline',
    'Restauración de Equipos',
    'Revitalice sus equipos antiguos o dañados con nuestros servicios de restauración especializados. Mejoramos la eficiencia y confiabilidad de su maquinaria, extendiendo su vida útil.',
    'people-outline',
    'Asesoría Técnica',
    'Optimice el uso y mantenimiento de sus equipos con la asesoría técnica especializada de nuestros expertos. Mejore la eficiencia y seguridad operativa de su maquinaria.',
    'school-outline',
    'Capacitación para Operadores',
    'Capacitación personalizada para operadores de equipos especializados. Mejore las habilidades de su personal y aumente la productividad con nuestros programas de formación técnica.',
    'settings-outline',
    'Reparación y Reacondicionamiento',
    'Servicios de reparación y reacondicionamiento de equipos para tendidos eléctricos. Minimice el tiempo de inactividad con nuestras soluciones de alta calidad y respuesta rápida. Contamos con repuestos originales y técnicos certificados.',
    'Diagnóstico gratuito',
    'Repuestos originales',
    'Garantía extendida',
    'Servicio a domicilio',
    'shield-checkmark-outline',
    'Mantenimiento Preventivo',
    'Asegure el rendimiento óptimo de sus equipos con nuestro servicio de mantenimiento preventivo. Inspecciones detalladas y ajustes programados para prolongar la vida útil de su maquinaria y evitar paradas no planificadas.',
    'Programación flexible',
    'Reportes detallados',
    'Historial de servicio',
    'Alertas preventivas',
    'time-outline',
    'Respuesta Rápida',
    'Servicio técnico de emergencia disponible 24/7 para atender sus necesidades urgentes y minimizar tiempos de inactividad.',
    'people-outline',
    'Técnicos Certificados',
    'Equipo altamente calificado y certificado con amplia experiencia en equipos especializados para tendidos eléctricos.',
    'shield-checkmark-outline',
    'Garantía de Calidad',
    'Todos nuestros servicios incluyen garantía extendida y seguimiento post-servicio para asegurar su satisfacción.',
    'analytics-outline',
    'Tecnología Avanzada',
    'Utilizamos equipos de diagnóstico de última generación para identificar y resolver problemas con precisión.',
    'cube-outline',
    'Repuestos Originales',
    'Trabajamos únicamente con repuestos originales y de alta calidad para garantizar el mejor rendimiento de sus equipos.',
    'cash-outline',
    'Precios Competitivos',
    'Cotizaciones transparentes y precios justos sin costos ocultos. Planes de mantenimiento con descuentos especiales.',
    'Proceso de Servicio',
    'Solicitud de Servicio',
    'Contáctanos por teléfono, email o formulario web. Describenos el problema y coordinaremos la visita técnica.',
    'Diagnóstico Técnico',
    'Nuestro técnico realizará una inspección completa y diagnóstico detallado del estado de su equipo.',
    'Cotización',
    'Recibirá una cotización clara y detallada con el costo de reparación, repuestos y tiempo estimado.',
    'Reparación',
    'Una vez aprobada la cotización, procedemos con la reparación utilizando repuestos originales de calidad.',
    'Pruebas y Entrega',
    'Realizamos pruebas exhaustivas para verificar el correcto funcionamiento antes de entregar el equipo.',
    'Seguimiento',
    'Realizamos seguimiento post-servicio para asegurar su satisfacción y el óptimo funcionamiento del equipo.',
    '¿Necesitas Servicio Técnico?',
    'Contáctanos ahora y uno de nuestros técnicos especializados te atenderá de inmediato',
    'Servicio de emergencia disponible 24/7'
);


